# Generated by Django 6.0.2 on 2026-02-21 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier')], default='CUSTOMER', help_text='Type of party: Customer or Supplier', max_length=10)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('gst_number', models.CharField(blank=True, help_text='Goods and Services Tax Number (for Indian businesses)', max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, help_text='Permanent Account Number (for Indian businesses)', max_length=10, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum credit allowed for this party', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'party_type'], name='core_party_name_353621_idx')],
            },
        ),
    ]
