# Generated by Django 6.0.2 on 2026-02-21 17:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('authors', models.CharField(help_text='Multiple authors can be separated by commas', max_length=500)),
                ('isbn', models.CharField(db_index=True, help_text='International Standard Book Number (10 or 13 digits)', max_length=13, unique=True)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('binding', models.CharField(choices=[('HARDCOVER', 'Hardcover'), ('PAPERBACK', 'Paperback'), ('SPIRAL', 'Spiral-bound'), ('EBOOK', 'E-book')], default='PAPERBACK', max_length=20)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Current selling price', max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Purchase cost from supplier', max_digits=10)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=5, help_text='Minimum quantity before reordering')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('shelf_location', models.CharField(blank=True, max_length=50)),
                ('is_in_print', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['isbn'], name='core_book_isbn_79f84d_idx'), models.Index(fields=['title', 'authors'], name='core_book_title_e02a69_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('SALES', 'Sales Invoice'), ('PURCHASE', 'Purchase Invoice'), ('SALES_RETURN', 'Sales Return'), ('PURCHASE_RETURN', 'Purchase Return')], default='SALES', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROFORMA', 'Proforma'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='DRAFT', max_length=20)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CREDIT', 'Credit (Account)')], default='CREDIT', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(help_text='Customer for sales, Supplier for purchases', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.party')),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage applied to this item', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='core.book')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='core_invoic_invoice_aef6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['party', 'invoice_date'], name='core_invoic_party_i_183c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='core_invoic_status_71224b_idx'),
        ),
    ]
